#!/bin/bash
set -eo pipefail

readonly REPO="$(cat release/repo)"
readonly VERSION="$(cat release/version)"
readonly NAME="$(cat release/name 2> /dev/null)"
readonly RELEASES_ENDPOINT="https://api.github.com/repos/$REPO/releases"
readonly ASSETS_ENDPOINT="https://uploads.github.com/repos/$REPO/releases/%s/assets"

main() {
	local files="release/${1:-"*.tgz"}"
	local upload_url=$(curl -s --fail -d "{\"tag_name\": \"v$VERSION\", \"name\":\"$NAME\"}" "$RELEASES_ENDPOINT?access_token=$GITHUB_ACCESS_TOKEN" | jq -r .upload_url | sed "s/[\{\}]//g")
	for file in $files; do
		local name="$(basename $file)"
		echo "$name"
		curl --fail -X POST -H "Content-Type: application/gzip" --data-binary "@$file" "$upload_url=$name&access_token=$GITHUB_ACCESS_TOKEN" > /dev/null
	done
}

main "$@"